[book]
title = "ibkr-porez"
authors = ["Andrey Sorokin"]
language = "ru"
src = "src"

[build]
build-dir = "../../site/ru"

[output.html]
git-repository-url = "https://github.com/andgineer/ibkr-porez"
