[book]
title = "ibkr-porez"
authors = ["Andrey Sorokin"]
language = "uk"
src = "src"

[build]
build-dir = "../../site/uk"

[output.html]
git-repository-url = "https://github.com/andgineer/ibkr-porez-rs"
additional-css = ["../theme/lang-switcher.css"]
additional-js = ["../theme/lang-switcher.js"]
